name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: use node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm ci
    - name: build  
      run: npm run build
    - name: test
      run: npm test
    - name: audit urls
      run: grep -roh 'http[s?]://[a-zA-Z0-9./\-\+\&\?\=]*' _site/**/*.html | sort | uniq | npx audit-urls
